### ISSUE TITLE
Idle Ball Creation

### ISSUE THREAD

**Issue by colecci** [MicMacro/ManyPong2#1]
This bug happens when you leave the ManyPong tab idle, then balls are created but the game logic is not updated.

I have an example of this bug as a screenshot and attached below, and a screen recording reproducing the bug: [https://soapbox.wistia.com/videos/rlJ8ZGPfGn/edit](https://soapbox.wistia.com/videos/rlJ8ZGPfGn/edit)

Here is the screenshot:
![manypong_glitch](https://user-images.githubusercontent.com/46729133/80870057-9fe10380-8c69-11ea-9acf-f5b500cc6c41.png)

mentions: @michaelfm1211

**Comment by michaelfm1211** [comment]
This bug is most likely due to the ball creation being inside a separate interval than the main draw loop.
